data_ingestion:
  root_dir: artifacts/data_ingestion
  source_dir: "C:/Users/Prachi/Downloads/chest_ct_scan_dataset"
  
data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion
  status_file: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_dir: artifacts/data_ingestion
  image_size: [224,224]
  batch_size: 32