data_ingestion:
  root_dir: artifacts/data_ingestion
  source_dir: "C:/Users/Prachi/Downloads/chest_ct_scan_dataset"
  
data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion
  status_file: artifacts/data_validation/status.txt